const builder = [
    [["arrow.png", 64]],
    [
        ["black_dye.png",       64],
        ["blue_dye.png",        64],
        ["brown_dye.png",       64],
        ["cyan_dye.png",        64],
        ["gray_dye.png",        64],
        ["green_dye.png",       64],
        ["light_blue_dye.png",  64],
        ["light_gray_dye.png",  64],
        ["lime_dye.png",        64],
        ["magenta_dye.png",     64],
        ["orange_dye.png",      64],
        ["pink_dye.png",        64],
        ["purple_dye.png",      64],
        ["red_dye.png",         64],
        ["white_dye.png",       64],
        ["yellow_dye.png",      64],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0],
        ["", 0]
    ],
]