const collection = [
    [
        ["music_disc_5.png",                1],
        ["music_disc_13.png",               1],
        ["music_disc_blocks.png",           1],
        ["music_disc_cat.png",              1],
        ["music_disc_chirp.png",            1],
        ["music_disc_creator.png",          1],
        ["music_disc_creator_music_box.png",1],
        ["music_disc_far.png",              1],
        ["music_disc_lava_chicken.png",     1],
        ["music_disc_mall.png",             1],
        ["music_disc_mellohi.png",          1],
        ["music_disc_otherside.png",        1],
        ["music_disc_pigstep.png",          1],
        ["music_disc_precipice.png",        1],
        ["music_disc_relic.png",            1],
        ["music_disc_stal.png",             1],
        ["music_disc_strad.png",            1],
        ["music_disc_tears.png",            1],
        ["music_disc_wait.png",             1],
        ["music_disc_ward.png",             1],
        ["music_disc_11.png",               1],
        ["music_disc_11.png",               1],
        ["music_disc_11.png",               1],
        ["music_disc_11.png",               1],
        ["music_disc_11.png",               1],
        ["music_disc_11.png",               1],
        ["music_disc_11.png",               1]
    ],
    [
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["ink_sac.png", 64],
        ["book.png",    64],
        ["book.png",    64],
        ["book.png",    64],
        ["book.png",    64],
        ["book.png",    64],
        ["book.png",    64],
        ["book.png",    64],
        ["book.png",    64],
        ["book.png",    64],
        ["feather.png", 64],
        ["feather.png", 64],
        ["feather.png", 64],
        ["feather.png", 64],
        ["feather.png", 64],
        ["feather.png", 64],
        ["feather.png", 64],
        ["feather.png", 64],
        ["feather.png", 64],
    ],
]