const pack = [
    {
        "NAME": "Торфин 2 сезон",
        "NOTE": "Аграрный монстр",
        "PRIC": 99,
        "MENU":[
            ["carrot",          64],
            ["potato",          64],
            ["wheat_seeds",     64],
            ["beetroot_seeds",  64],
            ["melon_seeds",     64],
            ["pumpkin_seeds",   64],
            ["nether_wart",     64],
            ["cocoa_beans",     64],
            ["bamboo",     64],
            ["sugar_cane",     64],
            ["../sapling/acacia_sapling",     64],
            ["../sapling/birch_sapling",     64],
            ["../sapling/cherry_sapling",     64],
            ["../sapling/dark_oak_sapling",     64],
            ["../sapling/jungle_sapling",     64],
            ["../sapling/oak_sapling",     64],
            ["../sapling/spruce_sapling",     64],
            ["../sapling/bamboo_stage0",     64],
            ["../b/cactus",          64],
            ["../b/chorus_flower",     64],
            ["../b/dirt",     64],
            ["../b/dirt",     64],
            ["../b/sand",     64],
            ["../b/sand",     64],
            ["../b/soul_sand",     64],
            ["../b/soul_sand",     64],
            ["../b/end_stone",     64]
        ]
    },
    {
        "NAME": "Художник",
        "NOTE": "Содержит все возможные красители",
        "PRIC": 99,
        "MENU":[
            ["black_dye",       64],
            ["blue_dye",        64],
            ["brown_dye",       64],
            ["cyan_dye",        64],
            ["gray_dye",        64],
            ["green_dye",       64],
            ["light_blue_dye",  64],
            ["light_gray_dye",  64],
            ["lime_dye",        64],
            ["magenta_dye",     64],
            ["orange_dye",      64],
            ["pink_dye",        64],
            ["purple_dye",      64],
            ["red_dye",         64],
            ["white_dye",       64],
            ["yellow_dye",      64],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0]
        ]
    }
]