const pack = [
    {
        "NAME": "Торфин 2 сезон",
        "NOTE": "Аграрный монстр",
        "PRIC": 99,
        "MENU":[
            ["carrot.png",          64],
            ["potato.png",          64],
            ["wheat_seeds.png",     64],
            ["beetroot_seeds.png",  64],
            ["melon_seeds.png",     64],
            ["pumpkin_seeds.png",   64],
            ["nether_wart.png",     64],
            ["cocoa_beans.png",     64],
            ["bamboo.png",     64],
            ["sugar_cane.png",     64],
            ["../sapling/acacia_sapling.png",     64],
            ["../sapling/birch_sapling.png",     64],
            ["../sapling/cherry_sapling.png",     64],
            ["../sapling/dark_oak_sapling.png",     64],
            ["../sapling/jungle_sapling.png",     64],
            ["../sapling/oak_sapling.png",     64],
            ["../sapling/spruce_sapling.png",     64],
            ["../sapling/bamboo_stage0.png",     64],
            ["../b/cactus.png",          64],
            ["../b/chorus_flower.png",     64],
            ["../b/dirt.png",     64],
            ["../b/dirt.png",     64],
            ["../b/sand.png",     64],
            ["../b/sand.png",     64],
            ["../b/soul_sand.png",     64],
            ["../b/soul_sand.png",     64],
            ["../b/end_stone.png",     64]
        ]
    },
    {
        "NAME": "Художник",
        "NOTE": "Содержит все возможные красители",
        "PRIC": 99,
        "MENU":[
            ["black_dye.png",       64],
            ["blue_dye.png",        64],
            ["brown_dye.png",       64],
            ["cyan_dye.png",        64],
            ["gray_dye.png",        64],
            ["green_dye.png",       64],
            ["light_blue_dye.png",  64],
            ["light_gray_dye.png",  64],
            ["lime_dye.png",        64],
            ["magenta_dye.png",     64],
            ["orange_dye.png",      64],
            ["pink_dye.png",        64],
            ["purple_dye.png",      64],
            ["red_dye.png",         64],
            ["white_dye.png",       64],
            ["yellow_dye.png",      64],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0],
            ["", 0]
        ]
    }
]